USE DB_SDE20_ARIEL_RANDIS;

SELECT * FROM VET_CLIENTES;
SELECT * FROM VET_CONSULTAS;
SELECT * FROM VET_PETS;

-- EXIBE NOME, TIPO E IDADE DE PETS COM MAIS DE 5 ANOS
SELECT NOME, TIPO_PET, IDADE FROM VET_PETS WHERE IDADE > 5;

-- EXIBE NOME, EMAIL E UF DE CLIENTES QUE MORAM NO ESTADO DE SP
SELECT NOME, EMAIL, UF FROM VET_CLIENTES WHERE UF = 'SP';