use DB_SDE20_ARIEL_RANDIS;

CREATE TABLE LOJA_BOLOS_PRODUTOS(
	ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	PRECO DECIMAL(10, 2) NOT NULL
);
CREATE TABLE LOJA_BOLOS_CLIENTES(
	ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(12),
    ENDERECO VARCHAR(100)
);
CREATE TABLE LOJA_BOLOS_VENDAS(
	ID_VENDA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    ID_CLIENTE INT,
    QUANTIDADE INT NOT NULL,
    DATA_VENDA DATE,
    FOREIGN KEY(ID_PRODUTO) REFERENCES LOJA_BOLOS_PRODUTOS(ID_PRODUTO),
    FOREIGN KEY(ID_CLIENTE) REFERENCES LOJA_BOLOS_CLIENTES(ID_CLIENTE)
);
CREATE TABLE LOJA_BOLOS_FORNECEDORES(
	ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(12) NOT NULL
);