USE DB_SDE20_ARIEL_RANDIS;

CREATE TABLE LANCHONETE_PRODUTOS(
	ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL
);
CREATE TABLE LANCHONETE_CLIENTES(
	ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL
);
CREATE TABLE LANCHONETE_PEDIDOS(
	ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    DATA_PEDIDO DATE NOT NULL,
    FOREIGN KEY(ID_PRODUTO) REFERENCES LANCHONETE_PRODUTOS(ID_PRODUTO),
    FOREIGN KEY(ID_CLIENTE) REFERENCES LANCHONETE_CLIENTES(ID_CLIENTE)
);
CREATE TABLE LANCHONETE_FORNECEDORES(
	ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL
);
