USE DB_SDE20_ARIEL_RANDIS;

CREATE TABLE IF NOT EXISTS VET_CLIENTES(
	ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR (50) NOT NULL UNIQUE,
    CIDADE VARCHAR (30),
    UF VARCHAR(2)
);
CREATE TABLE IF NOT EXISTS VET_PETS(
	ID_ANIMAL INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50),
    TIPO_PET VARCHAR(20) NOT NULL CHECK(TIPO_PET IN('Gato', 'Cachorro')),
    IDADE INT,
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES VET_CLIENTES(ID_CLIENTE)
);
CREATE TABLE IF NOT EXISTS VET_CONSULTAS(
	ID_CONSULTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_ANIMAL INT NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    MOTIVO VARCHAR(70),
    VALOR DECIMAL(10, 2),
    FOREIGN KEY (ID_ANIMAL) REFERENCES VET_PETS(ID_ANIMAL)
);
ALTER TABLE VET_CLIENTES CHANGE COLUMN  NOME NOME VARCHAR(51);