-- START TRANSACTION, SAVEPOINT, ROLLBACK, COMMIT
-- TRUNCATE TABLE - DELETAR ESPAÇO FÍSICO DA TABELA

USE DB_SDE20_ARIEL_RANDIS;

CREATE TABLE PRODUTOS (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    ESTOQUE INT NOT NULL
);
INSERT INTO PRODUTOS (NOME, PRECO, ESTOQUE) VALUES
	('Bolo de Fubá','5.50','10'),
	('Bolo de Morango','6.25','23'),
	('Torta de Maracujá','7.50','11'),
	('Suco de Caixa','4.20','64'),
	('Cookie de Chocolate','3.70','32'),
	('Empada de Frango','12.50','21'),
	('Agua Mineral','2.50','123'),
	('Suco de Uva Integral','9.90','98'),
	('Panetone','19.90','23'),
	('Café Capsula Expresso','12.45','398');
        
SELECT NOME, PRECO FROM PRODUTOS
WHERE PRECO > 5 ORDER BY PRECO ASC;

SELECT NOME, PRECO FROM PRODUTOS
WHERE NOME LIKE 'Bolo%'
ORDER BY PRECO DESC;

SELECT ID, NOME FROM PRODUTOS
WHERE ESTOQUE < 50
ORDER BY ID ASC;

SELECT ID, NOME FROM PRODUTOS
WHERE ESTOQUE BETWEEN
30 AND 100;

SELECT NOME, PRECO FROM PRODUTOS
WHERE NOME LIKE '%Bolo%' AND
PRECO < '6.00' OR
PRECO > 10
ORDER BY PRECO DESC;

SELECT * FROM PRODUTOS ORDER BY NOME ASC LIMIT 4;

DROP TABLE PRODUTOS;